Repository smallrye/smallrye-graphql, pull requests merged in 2022-09, with the labels that each got.

#1531 Remove reference to deprecated BeanManager#fireEvent()
  server/implementation-cdi/src/main/java/io/smallrye/graphql/cdi/event/EventsService.java
Labels: back-port

#1560 Support directives on input objects and input fields
  common/schema-builder/src/main/java/io/smallrye/graphql/schema/SchemaBuilder.java
  common/schema-builder/src/main/java/io/smallrye/graphql/schema/creator/type/InputTypeCreator.java
  server/implementation/src/main/java/io/smallrye/graphql/bootstrap/Bootstrap.java
  server/implementation/src/test/java/io/smallrye/graphql/schema/InputDirective.java
  server/implementation/src/test/java/io/smallrye/graphql/schema/InputTestApi.java
  server/implementation/src/test/java/io/smallrye/graphql/schema/SchemaTest.java
Labels: back-port

#1566 directives on interfaces
  server/implementation/src/main/java/io/smallrye/graphql/bootstrap/Bootstrap.java
  server/implementation/src/test/java/io/smallrye/graphql/schema/DirectivesTestApi.java
  server/implementation/src/test/java/io/smallrye/graphql/schema/SchemaTest.java
  server/implementation/src/test/java/io/smallrye/graphql/schema/TestInterfaceDirective.java
  server/implementation/src/test/java/io/smallrye/graphql/schema/TestInterfaceDirectiveImpl.java
  server/implementation/src/test/resources/schemaTest.graphql
Labels: back-port

#1569 fix #1563: map input Java `Instant` to GraphQL scalar `DateTime`
  client/implementation/src/main/java/io/smallrye/graphql/client/impl/typesafe/reflection/ParameterInfo.java
  client/tck/src/main/java/tck/graphql/typesafe/ScalarBehavior.java
Labels: bug, Client

#1575 #1570: add executionResult field to SmallRyeContext
  server/implementation/src/main/java/io/smallrye/graphql/execution/ExecutionService.java
  server/implementation/src/main/java/io/smallrye/graphql/execution/context/SmallRyeContext.java
  server/implementation/src/test/java/io/smallrye/graphql/execution/context/SmallRyeContextTest.java
Labels: enhancement, back-port

#1132 #521: add federation to core:
  README.adoc
  docs/federation.md
  mkdocs.yml
  pom.xml
  server/api/src/main/java/io/smallrye/graphql/api/federation/Extends.java
  server/api/src/main/java/io/smallrye/graphql/api/federation/External.java
  server/api/src/main/java/io/smallrye/graphql/api/federation/Key.java
  server/api/src/main/java/io/smallrye/graphql/api/federation/Provides.java
  server/api/src/main/java/io/smallrye/graphql/api/federation/Requires.java
  server/federation/README.adoc
  server/federation/api/pom.xml
  server/federation/api/src/main/java/io/smallrye/graphql/federation/api/FederatedSource.java
  server/federation/pom.xml
  server/federation/runtime/pom.xml
  server/federation/runtime/src/main/java/io/smallrye/graphql/federation/impl/Federation.java
  server/implementation-cdi/src/main/java/io/smallrye/graphql/cdi/config/ConfigKey.java
  server/implementation-cdi/src/main/java/io/smallrye/graphql/cdi/config/MicroProfileConfig.java
  server/implementation/pom.xml
  server/implementation/src/main/java/io/smallrye/graphql/SmallRyeGraphQLServerLogging.java
  server/implementation/src/main/java/io/smallrye/graphql/bootstrap/Bootstrap.java
  server/implementation/src/main/java/io/smallrye/graphql/bootstrap/FederationDataFetcher.java
  server/implementation/src/main/java/io/smallrye/graphql/execution/ExecutionResponse.java
  server/implementation/src/main/java/io/smallrye/graphql/spi/config/Config.java
  server/implementation/src/test/java/io/smallrye/graphql/execution/TestConfig.java
  server/implementation/src/test/java/io/smallrye/graphql/schema/FederationTestApi.java
  server/implementation/src/test/java/io/smallrye/graphql/schema/SchemaTest.java
  server/implementation/src/test/java/io/smallrye/graphql/schema/TestTypeWithFederation.java
  server/pom.xml
  server/runner/src/main/resources/META-INF/microprofile-config.properties
  server/tck/src/test/java/io/smallrye/graphql/SmallRyeGraphQLArchiveProcessor.java
  server/tck/src/test/java/io/smallrye/graphql/test/apps/federation/ProductApi.java
  server/tck/src/test/java/io/smallrye/graphql/test/apps/federation/ProductEntity.java
  server/tck/src/test/resources/META-INF/microprofile-config.properties
  server/tck/src/test/resources/tests/federation/input.graphql
  server/tck/src/test/resources/tests/federation/output.json
  server/tck/src/test/resources/tests/federation/test.properties
Labels: back-port
