Repository smallrye/smallrye-graphql, pull requests merged in 2023-01, with the labels that each got.

#1669 maven-cache the github setup-java action
  .github/workflows/build.yml
Labels: forward-port-mutiny2

#1677 Increase timeouts in DynamicClientSSLTestCase, use try-with-resources
  client/implementation-vertx/src/test/java/io/smallrye/graphql/client/vertx/test/ssl/DynamicClientSSLTest.java
Labels: back-port, forward-port-mutiny2

#1701 activate test
  common/schema-builder/src/test/java/io/smallrye/graphql/schema/helper/NonNullHelperTest.java
Labels: back-port, forward-port-mutiny2

#1705 Fix some error handling in subscriptions over websockets
  client/implementation-vertx/src/main/java/io/smallrye/graphql/client/vertx/websocket/graphqlws/MessageType.java
  server/implementation/src/main/java/io/smallrye/graphql/websocket/AbstractGraphQLWebsocketHandler.java
  server/implementation/src/main/java/io/smallrye/graphql/websocket/graphqlws/MessageType.java
  server/integration-tests/src/test/java/io/smallrye/graphql/tests/client/dynamic/subscription/AbstractDynamicClientSubscriptionTest.java
  server/integration-tests/src/test/java/io/smallrye/graphql/tests/client/dynamic/subscription/DynamicClientSubscriptionApi.java
  server/integration-tests/src/test/java/io/smallrye/graphql/tests/client/typesafe/subscription/AbstractTypesafeClientSubscriptionTest.java
  server/integration-tests/src/test/java/io/smallrye/graphql/tests/client/typesafe/subscription/SubscriptionApi.java
  server/integration-tests/src/test/java/io/smallrye/graphql/tests/client/typesafe/subscription/SubscriptionClientApi.java
  ui/graphiql/src/main/webapp/render.js
Labels: forward-port, forward-port-mutiny2
